# tomcat配置
server:
  port: 8080
  contextPath: /

  # Tomcat specifics
  tomcat:
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs

#spring profile环境配置
spring:
  profiles: dev
datasource:
  url: jdbc:mysql://localhost/test
  username: root
  password: root
  driver-class: com.mysql.jdbc.Driver
---
spring:
  profiles: test
datasource:
  url: jdbc:mysql://localhost/test
  username: root
  password: root
  driver-class: com.mysql.jdbc.Driver